@echo off
%~d0
cd %~dp0
call setup.cmd
rem start dagor3_cdk\bin64\daEditor3x-dev.exe -ws:WarThunderMissionEditor -lateSceneSelect -no_src_assets levels/mission_editor_location/mission_editor_location.level.blk "-enable:(srv) Grass" -exclude_dll_re:heightmap -disable:Landscape -disable:Collision -disable:Occluders -disable:ScnExport -disable:SGeometry "-disable:(srv) Phys object entities" "-disable:(srv) Prefab entities" "-disable:(filter) Distinct entities" "-disable:(filter) Generated by polygon" "-disable:(filter) Generated by landclass map" "-disable:(filter) Generated by spline" "-disable:(filter) Road geom and objects" "-disable:(filter) CSG"
start dagor3_cdk\bin64\daEditor3x-dev.exe -ws:WarThunderMissionEditor -lateSceneSelect "-enable:(srv) Grass" -exclude_dll_re:heightmap -disable:Landscape -disable:Collision -disable:Occluders -disable:ScnExport -disable:SGeometry "-disable:(srv) Phys object entities" "-disable:(srv) Prefab entities" "-disable:(filter) Distinct entities" "-disable:(filter) Generated by polygon" "-disable:(filter) Generated by landclass map" "-disable:(filter) Generated by spline" "-disable:(filter) Road geom and objects" "-disable:(filter) CSG"
